baseURL = 'https://saraswaminathan.com/'
languageCode = 'en-us'
title = 'Sara Swaminathan, PhD'
theme = "my-theme"
canonifyURLs = true

[params]
macyJsCDN = "https://cdn.jsdelivr.net/npm/macy@2" # image gallery library

[markup.goldmark.renderer]
unsafe = true

[menus]
[[menus.main]]
name = 'About Me'
pageRef = '/info'
weight = 10

[[menus.main]]
name = 'CV'
pageRef = '/cv'
weight = 20

[[menus.main]]
name = 'Education and Outreach'
pageRef = '/educationOutreach'
weight = 30

[[menus.main]]
name = 'Gallery'
pageRef = '/gallery'
weight = 40
